rm -f /home/eli/android/qt5/armv7/lib/*Qt*AV*
rm -f /home/eli/android/qt5/armv7/lib/libQt5AV.so
rm -rf /home/eli/android/qt5/armv7/include/QtAV
rm -f /home/eli/android/qt5/armv7/mkspecs/features/av.prf
rm -f /home/eli/android/qt5/armv7/mkspecs/modules/qt_lib_av*.pri
rm -f /home/eli/android/qt5/armv7/lib/libcommon.so
rm -f /home/eli/android/qt5/armv7/lib/*Qt*AV*
rm -f /home/eli/android/qt5/armv7/lib/libQt5AVWidgets.so
rm -rf /home/eli/android/qt5/armv7/include/QtAVWidgets
rm -f /home/eli/android/qt5/armv7/mkspecs/features/avwidgets.prf
rm -f /home/eli/android/qt5/armv7/mkspecs/modules/qt_lib_avwidgets*.pri
rm -f /home/eli/android/qt5/armv7/lib/libcommon.so
rm -rf /home/eli/android/qt5/armv7/qml/QtAV
